apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: example

data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 54.176.125.151
        - 54.176.125.151
        - 13.56.79.252
